channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=25.2
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - lz4==3.1.3
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
