name: CI - MLFlow with DagsHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'   # ✅ enables pip caching

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run training script with DagsHub auth
      - name: Run ML experiment
        env:
          DAGSHUB_USERNAME: aHp16
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: python src/file.py

      # Run tests
      - name: Run tests
        run: pytest -v

      # Upload MLflow logs as artifacts
      - name: Upload MLflow artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-logs
          path: mlruns/
